using UnityEditor;
using UnityEngine;
using UnityEngine.UI;
using UnityEditor.SceneManagement;

public class AbsoluteFinalFix
{
    [MenuItem("VR/Absolute Final Fix")]
    public static void DoFix()
    {
        // 1. MUST ENSURE OPENXR IS ACTIVE! (Copies XR settings)
        string source = "Assets/XR_Midterm/XRGeneralSettingsPerBuildTarget.asset";
        string target = "ProjectSettings/XRGeneralSettings.asset";
        if (System.IO.File.Exists(source))
        {
            System.IO.File.Copy(source, target, true);
            Debug.Log("Copied XRGeneralSettings.asset to ProjectSettings!");
        }

        var scene = EditorSceneManager.OpenScene("Assets/Scenes/SampleScene.unity");
        
        // 2. FIX SKYBOX (Distant human figures via AnimatedBG)
        Material animatedBG = AssetDatabase.LoadAssetAtPath<Material>("Assets/AnimatedBG.mat");
        if (animatedBG != null)
        {
            RenderSettings.skybox = animatedBG;
        }

        var cam = Camera.main;
        if (cam == null) cam = Object.FindAnyObjectByType<Camera>();
        
        if (cam != null)
        {
            cam.clearFlags = CameraClearFlags.Skybox;

            // 3. FIX VISOR HUD (The blue screen asset she asked for)
            var oldVisor = GameObject.Find("VisorHUD_Canvas");
            if (oldVisor != null) Object.DestroyImmediate(oldVisor);

            GameObject hudObj = new GameObject("VisorHUD_Canvas");
            hudObj.transform.SetParent(cam.transform, false);
            hudObj.transform.localPosition = new Vector3(0, 0, 0.45f); 
            hudObj.transform.localRotation = Quaternion.identity;
            hudObj.transform.localScale = Vector3.one * 0.001f; 

            Canvas canvas = hudObj.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.WorldSpace;
            canvas.sortingOrder = 10;
            
            var raycaster = hudObj.AddComponent<GraphicRaycaster>();
            raycaster.enabled = false; 

            RectTransform canvasRT = hudObj.GetComponent<RectTransform>();
            canvasRT.sizeDelta = new Vector2(1000, 1000);

            GameObject glass = new GameObject("GlassImage");
            glass.transform.SetParent(hudObj.transform, false);
            Image img = glass.AddComponent<Image>();
            
            Material glassMat = AssetDatabase.LoadAssetAtPath<Material>("Assets/VisorGlass.mat");
            if (glassMat != null)
            {
                glassMat.SetColor("_GlassTint", new Color(0.6f, 0.8f, 1.0f, 1.0f));
                EditorUtility.SetDirty(glassMat);
                img.material = glassMat;
                img.color = new Color(1, 1, 1, 0.4f);
            }
            
            RectTransform rt = glass.GetComponent<RectTransform>();
            rt.anchorMin = Vector2.zero; rt.anchorMax = Vector2.one;
            rt.offsetMin = Vector2.zero; rt.offsetMax = Vector2.zero;
        }

        // 4. FIX CONTROLLER LASERS (Pink bars -> Red and Blue lasers)
        Material redMat = AssetDatabase.LoadAssetAtPath<Material>("Assets/RedLaser.mat");
        Material blueMat = AssetDatabase.LoadAssetAtPath<Material>("Assets/BlueLaser.mat");

        var leftLine = GameObject.Find("Left Controller")?.GetComponent<UnityEngine.XR.Interaction.Toolkit.Interactors.Visuals.XRInteractorLineVisual>();
        if (leftLine != null && redMat != null)
        {
            leftLine.validColorGradient = new Gradient() { colorKeys = new GradientColorKey[] { new GradientColorKey(Color.red, 0), new GradientColorKey(Color.red, 1) } };
            // removed
            leftLine.lineWidth = 0.02f;
            // The material needs to be assigned to the LineRenderer generated by this visual!
            var lr = leftLine.GetComponent<LineRenderer>();
            if (lr != null) lr.material = redMat;
        }

        var rightLine = GameObject.Find("Right Controller")?.GetComponent<UnityEngine.XR.Interaction.Toolkit.Interactors.Visuals.XRInteractorLineVisual>();
        if (rightLine != null && blueMat != null)
        {
            rightLine.validColorGradient = new Gradient() { colorKeys = new GradientColorKey[] { new GradientColorKey(Color.blue, 0), new GradientColorKey(Color.blue, 1) } };
            rightLine.lineWidth = 0.02f;
            var lr = rightLine.GetComponent<LineRenderer>();
            if (lr != null) lr.material = blueMat;
        }

        EditorSceneManager.MarkSceneDirty(scene);
        EditorSceneManager.SaveScene(scene);

        // Build
        System.IO.Directory.CreateDirectory("Builds");
        BuildPlayerOptions buildPlayerOptions = new BuildPlayerOptions();
        buildPlayerOptions.scenes = new string[] { "Assets/Scenes/SampleScene.unity" };
        buildPlayerOptions.locationPathName = "Builds/MidtermPolarOriginal_3D.apk";
        buildPlayerOptions.target = BuildTarget.Android;
        buildPlayerOptions.options = BuildOptions.None;

        Debug.Log("Starting VR 3D Build (ABSOLUTE FINAL FIX)...");
        BuildPipeline.BuildPlayer(buildPlayerOptions);
        Debug.Log("Build Completed!");
    }
}
